# ==============================================================================
# FILE: infra/docker-compose.yml
# (Tạo file này trong thư mục infra: dr-drill-app/infra/docker-compose.yml)
# ==============================================================================

version: '3.8'

services:
  db:
    image: postgres:16
    container_name: dr-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-dr_drill}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  storage:
    image: minio/minio:latest
    container_name: dr-storage
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile
    container_name: dr-backend
    depends_on:
      - db
      - storage
    ports:
      - "3001:3001"
    env_file:
      - ../.env
    volumes:
      - ../apps/backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ..
      dockerfile: apps/frontend/Dockerfile
    container_name: dr-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ../apps/frontend:/app
      - /app/.next
      - /app/node_modules

volumes:
  postgres_data:
  minio_data:

